title: Auralis Group
email: info@auralispartners.com
description: We change the way software is built.
baseurl: /
url: https://auralis.group
meta_image: /assets/auralis_meta.png
keywords: auralis, auralis group, auralis partners, software development, software engineering, software architecture, software consulting, software solutions, consulting, venture studio, startup builder, teams as a service, tech recruiting, tech investment
sass:
  quiet_deps: true
content:
  nav:
  - id: home
    name: Home
    link: /
  - id: services
    name: Services
    link: /services/
  - id: team
    name: Meet the Team
    link: /team/
  - id: about
    name: About Us
    link: /about-us/
  - id: careers
    name: Careers
    link: /careers/
  - id: case-studies
    name: Case Studies
    link: /case-studies/
  - id: blog
    name: Blog
    link: /blog/
  logos:
  - src: /assets/logos/advastore_logo.png
    name: advastore
  - src: /assets/logos/atlas_elektronik.png
    name: Atlas Elektronik
  - src: /assets/logos/axiros_logo.png
    name: Axiros
  - src: /assets/logos/bestsecret_logo.png
    name: BESTSECRET
  - src: /assets/logos/bg_phoenics_logo.jpeg
    name: BG Phoenics
  - src: /assets/logos/bilfinger_logo.jpeg
    name: Bilfinger
  - src: /assets/logos/btv.png
    name: BTV
  - src: /assets/logos/bundesagentur_fuer_arbeit_logo.png
    name: Bundesagentur für Arbeit
  - src: /assets/logos/bwi_logo.png
    name: BWI IT für Deutschland
  - src: /assets/logos/cariad_logo.png
    name: Cariad
  - src: /assets/logos/Deutsche_Bahn.png
    name: Deutsche Bahn
  - src: /assets/logos/deutsche_telekom_logo.png
    name: Deutsche Telekom
  - src: /assets/logos/deutz_logo.png
    name: Deutz
  - src: /assets/logos/eon_logo.png
    name: e.on
  - src: /assets/logos/envia_logo.png
    name: envia M
  - src: /assets/logos/fratch_logo.png
    name: Fratch
  - src: /assets/logos/geberit_logo.png
    name: Geberit
  - src: /assets/logos/hitachi_logo.svg
    name: Hitachi
  - src: /assets/logos/infineon_logo.svg
    name: Infineon
  - src: /assets/logos/jysk_logo.jpg
    name: Jysk
  - src: /assets/logos/kion_group_logo.png
    name: KION Group
  - src: /assets/logos/koerber_logo.png
    name: Körber
  - src: /assets/logos/landesapothekerkammer_bw_logo.png
    name: Landesapothekerkammer Baden-Württemberg
  - src: /assets/logos/miele_logo.png
    name: Miele
  - src: /assets/logos/ntt_logo.png
    name: NTT
  - src: /assets/logos/nunatak.png
    name: Nunatak
  - src: /assets/logos/promantis_logo.png
    name: promantis
  - src: /assets/logos/rewe_logo.png
    name: REWE
  - src: /assets/logos/rheinmetall_logo.png
    name: Rheinmetall
  - src: /assets/logos/swarco_logo.png
    name: Swarco
  - src: /assets/logos/Thales_Logo.svg
    name: Thales
  - src: /assets/logos/trianel_logo.svg
    name: Trianel
  - src: /assets/logos/uniper_logo.png
    name: Uniper
  - src: /assets/logos/vhv_versicherungen_logo.svg
    name: VHV Versicherungen
  - src: /assets/logos/volkswagen_logo.png
    name: Volkswagen
  - src: /assets/logos/vonovia_logo.png
    name: Vonovia
  - src: /assets/logos/vorwerk_logo.png
    name: Vorwerk
  - src: /assets/logos/westenergie_logo.png
    name: westenergie
  # Add new cities via: https://www.openstreetmap.org/#map=13, search for city name, right click `show address`. Use the lat/lon from the city center
  cities:
  - name: Aachen
    lat: 50.77788
    lon: 6.08316
  - name: Altenbeken-Schwaney
    lat: 51.713682
    lon: 8.934862
  - name: Arnstadt
    lat: 50.83426
    lon: 10.94564
  - name: Bad Urach
    lat: 48.49453
    lon: 9.39803
  - name: Baesweiler
    lat: 50.90880
    lon: 6.18221
  - name: Berlin
    lat: 52.51875
    lon: 13.39465
  - name: Bielefeld
    lat: 52.0218
    lon: 8.5309
  - name: Bocholt
    lat: 51.84230
    lon: 6.61583
  - name: Bochum
    lat: 51.48336
    lon: 7.21956
  - name: Burglauer
    lat: 50.3245
    lon: 10.0782
  - name: Cadolzburg
    lat: 49.46316
    lon: 10.85466
  - name: Darmstadt-Dieburg
    lat: 49.89892
    lon: 8.83893
  - name: Dippoldiswalde
    lat: 50.89843
    lon: 13.66253
  - name: Dümpelfeld
    lat: 50.44338
    lon: 6.93306
  - name: Düsseldorf
    lat: 51.2324
    lon: 6.7755
  - name: Erbach
    lat: 48.32889
    lon: 9.89164
  - name: Essen
    lat: 51.458266
    lon: 7.015819
  - name: Freiburg im Breisgau
    lat: 48.0004
    lon: 7.8528
  - name: Fulda
    lat: 50.55539
    lon: 9.67698
  - name: Furth im Wald
    lat: 49.31133
    lon: 12.84508
  - name: Garching
    lat: 48.25517
    lon: 11.65237
  - name: Geislingen
    lat: 48.62483
    lon: 9.83826
  - name: Hamburg
    lat: 53.590
    lon: 10.025
  - name: Hanau
    lat: 50.1464
    lon: 8.9133
  - name: Hürth
    lat: 50.8861
    lon: 6.8771
  - name: Karlsruhe
    lat: 49.01015
    lon: 8.40145
  - name: Kaufungen
    lat: 51.28650
    lon: 9.61982
  - name: Köln
    lat: 50.9419
    lon: 6.9626
  - name: Leipzig
    lat: 51.34085
    lon: 12.37462
  - name: Ludwigshafen
    lat: 49.47060
    lon: 8.43797
  - name: Mannheim
    lat: 49.489381
    lon: 8.467342
  - name: München
    lat: 48.1422
    lon: 11.5755
  - name: Münster
    lat: 51.9681
    lon: 7.6238
  - name: Neuwied
    lat: 50.43287
    lon: 7.46761
  - name: Oberickelsheim
    lat: 49.601670
    lon: 10.136336
  - name: Panketal
    lat: 52.64961
    lon: 13.54099
  - name: Pinneberg
    lat: 53.661613
    lon: 9.796747
  - name: Prittriching
    lat: 48.2063
    lon: 10.9286
  - name: Saarlouis
    lat: 49.315631
    lon: 6.750444
  - name: Schönwalde-Glien
    lat: 52.64095
    lon: 13.05038
  - name: Stuttgart
    lat: 48.7865
    lon: 9.1767
  - name: Tübingen
    lat: 48.52408
    lon: 9.05411
  - name: Vörstetten
    lat: 48.06568
    lon: 7.84939
  - name: Waldkirchen
    lat: 48.73250
    lon: 13.60073
  - name: Weingarten
    lat: 49.051963
    lon: 8.531259
  - name: Wolfsburg
    lat: 52.42470
    lon: 10.78583
  - name: Würzburg
    lat: 49.794497
    lon: 9.929337
theme: minima
plugins:
- jekyll-feed
- jekyll-sitemap
